neo4j/docs-getting-started

modules/ROOT/pages/cypher-intro/schema.adoc
modules/ROOT/pages/graphdb-concepts.adoc

Fixes a couple of links from the Getting Started Guide to the Cypher Manual where the target file has a new path.

fix two links to the cypher manual

---

modules/ROOT/pages/cypher-intro/load-csv.adoc

Reformats a link to the operations manual as `xref:`

fix link to operations manual

---

modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/cypher-intro/schema.adoc
modules/ROOT/pages/get-started-with-neo4j.adoc
modules/ROOT/pages/graphdb-concepts.adoc

The version attribute for Neo4j manuals has been changed from `4.4-preview` to `4.4`.
This PR updates xrefs from the Getting Started Guide to other Neo4j manuals to target the 4.4 version of the relevant manual.

Change xrefs from 4.4-preview to 4.4

---

modules/ROOT/pages/graph-database.adoc
modules/ROOT/pages/graphdb-vs-rdbms.adoc

Adds `ifndef::backend-pdf[]` conditions to prevent the passthrough html from being included in the PDF.
Also, in _modules/ROOT/pages/graphdb-vs-rdbms.adoc_ removes a blank line before the `:description:` attribute so it is included as part of the asciidoc [document header](https://docs.asciidoctor.org/asciidoc/latest/document/header/).

add conditional to exclude youtube embeds from pdf

---

modules/ROOT/pages/appendix/graphdb-concepts/index.adoc
modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/cypher-intro/schema.adoc
preview.yml
publish.yml

Updates `xref:` macros that point to other manuals so that they use the `link:` macro instead.
This allows the getting-started content to be built and published independently.
Also adds two new attributes to playbooks. In preview.yml, as follows:
```
neo4j-base-uri: https://neo4j.com # this attribute should be an empty string in publish.yml
neo4j-docs-base-uri: https://neo4j.com/docs # this attribute should be an empty string in publish.yml
```
Using these attributes users can build locally (with `preview.yml`) and test links to live neo4j.com/docs URLs. The `neo4j-docs-base-uri` is only `docs/` in `publish.yml` because this resolves relative to neo4j.com when published.

4.4-xrefs-to-links

---

antora.yml
modules/ROOT/pages/appendix/example-data.adoc
modules/ROOT/pages/appendix/getting-started-resources.adoc
modules/ROOT/pages/appendix/tutorials/guide-cypher-basics.adoc
modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
modules/ROOT/pages/cypher-intro/large-statements.adoc
modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
modules/ROOT/pages/cypher-intro/procedures-functions.adoc
modules/ROOT/pages/cypher-intro/results.adoc
modules/ROOT/pages/cypher-intro/updating.adoc
modules/ROOT/pages/data-import/csv-import.adoc
modules/ROOT/pages/data-import/index.adoc
modules/ROOT/pages/data-import/relational-to-graph-import.adoc
modules/ROOT/pages/data-modeling/index.adoc
modules/ROOT/pages/data-modeling/modeling-tips.adoc
modules/ROOT/pages/data-modeling/relational-to-graph-modeling.adoc
modules/ROOT/pages/graph-visualization/graph-visualization-tools.adoc
modules/ROOT/pages/graph-visualization/graph-visualization.adoc
modules/ROOT/pages/languages-guides/java/java-intro.adoc
modules/ROOT/pages/languages-guides/java/java-third-party.adoc
modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
modules/ROOT/pages/languages-guides/java/spring-data-neo4j.adoc
modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
modules/ROOT/pages/languages-guides/neo4j-erlang-elixir.adoc
modules/ROOT/pages/languages-guides/neo4j-go.adoc
modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
modules/ROOT/pages/languages-guides/neo4j-perl.adoc
modules/ROOT/pages/languages-guides/neo4j-php.adoc
modules/ROOT/pages/languages-guides/neo4j-python.adoc
modules/ROOT/pages/languages-guides/neo4j-ruby.adoc

Fixes issues reported in the Antora log, such as bad xrefs and missing attributes.
Remaining log messages are:
- xrefs to Operations manual and Cypher manual, which are addressed by #115
- missing attribute `neo4j-docs-base-uri`. also addressed by #115
- `expected substitution value for custom inline macro` error, which will be addressed by a future PR updating the package dependency versions.

Clean up Antora asciidoc warnings and errors

---

modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/cypher-intro/schema.adoc
modules/ROOT/pages/get-started-with-neo4j.adoc
modules/ROOT/pages/graphdb-concepts.adoc
preview.yml

Replaces `xref:` to other manuals with `link:` as for #115

Replace external xrefs with link macros

---

publish.yml

Updates the publish playbook with the correct path for links to pages in other manuals

Fix uri attribute for linking to other manuals

---

modules/ROOT/pages/cypher-intro/results.adoc

In Neo4j 5, Cypher syntax has been changed. It impacts some examples in the GSG.

Update the Cypher example according to the 5.0 syntax changes

---

modules/ROOT/pages/index.adoc

Move the documentation license to the bottom of the first page (according to the discussions)

Move the license to the bottom of the page

---

modules/ROOT/pages/cypher-intro/results.adoc
modules/ROOT/pages/get-started-with-neo4j/index.adoc
modules/ROOT/pages/integration-tools/integration.adoc
modules/ROOT/pages/languages-guides/index.adoc
modules/ROOT/pages/languages-guides/java/java-intro.adoc
modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
modules/ROOT/pages/languages-guides/neo4j-go.adoc
modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
modules/ROOT/pages/languages-guides/neo4j-python.adoc

Replace 'Causal Cluster' by 'Cluster'.
Change link to the Kafka Connector manual on the docs page.
Some small tweaks in different sections.

Fix the cluster terminology for v5

---

publish.yml

Following a long discussion on whether the GSG should be unversioned or not, it was decided to remove unsupported versions from the version checker. Only the long-term supported version and the currently supported version remain. In our case it's 4.4 and 5.x versions.

Remove versions except LTS and CS

---

publish.yml

Following a long discussion on whether the GSG should be unversioned or not, it was decided to remove unsupported versions from the version checker. Only the long-term supported version and the currently supported version remain. In our case it's 4.4 and 5.x versions.

Remove versions except for LTS and CS

---

modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/235

fixing link to neotypes docs, now instead leading to main page (#235)

---

modules/ROOT/pages/cypher-intro/schema.adoc

Add the registered trademark icon on the first usage of Cypher on every page of the manual

Fix the broken links to the Cypher manual (#269)

---

modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-rdbms.adoc
modules/ROOT/pages/appendix/graphdb-concepts/index.adoc
modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc
modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/data-import/relational-to-graph-import.adoc
modules/ROOT/pages/data-modeling/modeling-designs.adoc

Hey :wave:,
This PR will fix :
1 typo in `modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-rdbms.adoc`
2 typos in `modules/ROOT/pages/appendix/graphdb-concepts/index.adoc`
1 typo in `modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc`
1 typo in `modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc`
1 typo in `modules/ROOT/pages/cypher-intro/load-csv.adoc`
1 typo in `modules/ROOT/pages/data-import/relational-to-graph-import.adoc`
1 typo in `modules/ROOT/pages/data-modeling/modeling-designs.adoc`
Best!

docs: fix typos

---

modules/ROOT/pages/cypher-intro/results.adoc

Usage of `and` should be replaced with `or` for this case, as per the description: "users who have a Twitter account and who like graphs or query languages"

Fix or/and typo in query with 'WITH'

---

modules/ROOT/pages/cypher-intro/results.adoc

"and" should replace "or" in this case

Fix typo or/and in query with 'WITH' (#297)

---

modules/ROOT/pages/appendix/graphdb-concepts/index.adoc

Fix small omission of the "release" prop for the "Movie" on the Cypher example to match de graph viz.
Page: https://neo4j.com/docs/getting-started/appendix/graphdb-concepts/#graphdb-example-graph
refers to current graph svg uri:
https://neo4j.com/docs/getting-started/_images/graph_simple-arr.svg

Update index.adoc Cypher example

---

modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc

As `BTREE` indexes were removed and replaced by indexes of other types, we have to update code blocks and results in the corresponding section of the tutorial _Import data from a relational database into Neo4j_.

Update Cypher syntax for showing indexes

---

modules/ROOT/pages/data-import/csv-import.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/363

Fixing broken link to the cypher manual (#363)

---

modules/ROOT/pages/appendix/example-data.adoc

We definitely have to remove section on the Aura example datasets as they were replaced by the Workspace guides.
Probably we can add information about them.

Update example datasets page

---

modules/ROOT/pages/data-import/csv-import.adoc

adds a warning against allowing insecure protocols for `LOAD CSV`
this PR is the getting-started manual copy of the [cypher manual equivalent](https://github.com/neo4j/docs-cypher/pull/1006)

adding health warning about insecure protocols for LOAD CSV 

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/appendix/tutorials/tutorials-overview.adoc

After rule that every page needs to be listed in content-nav for it to load.

Adding tutorials to content-nav in order to fix broken links

---

modules/ROOT/pages/languages-guides/community-drivers/index.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/441

Add the rust driver to the list of community drivers (#441)
