neo4j/docs-getting-started

modules/ROOT/pages/index.adoc

Improved the header and added a sub header.
Added some more content on the front page.
Added license for pdf content.

improved the front page

---

modules/ROOT/pages/index.adoc

Improved the header and added a sub header.
Added some more content on the front page.
Added licence for pdf content.

improved the front page (#23)

---

package-lock.json
package.json

The npm package edge needed an updated version.

updated package files.

---

modules/ROOT/pages/get-started-with-neo4j.adoc

Improved get stared with neo4j page.

Improved get stared with neo4j page. (#29)

---

modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/cypher-intro/large-statements.adoc
modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
modules/ROOT/pages/cypher-intro/patterns.adoc
modules/ROOT/pages/cypher-intro/results.adoc
modules/ROOT/pages/cypher-intro/schema.adoc

Improved asciidoc and minor fixups.

4.4 improve getting started with cypher

---

modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/cypher-intro/large-statements.adoc
modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
modules/ROOT/pages/cypher-intro/patterns.adoc
modules/ROOT/pages/cypher-intro/results.adoc
modules/ROOT/pages/cypher-intro/schema.adoc

Improved the asciidoc and minor fixes.

4.4 improve getting started with cypher (#44)

---

modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/cypher-intro/schema.adoc

`CREATE CONSTRAINT ON ... ASSERT ...`
Changed in `4.4` to
`CREATE CONSTRAINT FOR ... REQUIRE ...`

Cypher syntax change

---

modules/ROOT/pages/cypher-intro/schema.adoc

Remove deprecated note about schema syntax.

Remove deprecated note in schema page

---

preview.yml

Amend copyright year to 2022

---

modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/graphdb-concepts.adoc

Fixed typos

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/getting-started-resources.adoc

new chapter is based on the dev.guide "Getting started resources". New links to the GraphAcademy courses were added + new info on Neo4j Community forums and chat on Discord.

add new chapter "Getting started resources"

---

modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc

I didn't include sections "Next steps", "Resources", and description of the dev.guide.

Add info to "Patterns in practice" from "Querying with Cypher"

---

modules/ROOT/pages/index.adoc

* Move the license to the bottom of the page

Move the license to the bottom of the page (#138)

---

modules/ROOT/pages/data-import/csv-import.adoc

- Update the content and code blocks.
- Instead of `PERIODIC COMMIT` use `CALL {...} IN TRANSACTIONS`
- `neo4j-admin import` is replaced by `neo4j-admin import database`

Update the chapter according to the syntax changes of v5

---

antora.yml

Fixes broken links to  _..../4.0/..._ pages of other Neo4j manuals

Quote numbers in antora.yml attributes

---

modules/ROOT/pages/cypher-intro/subqueries.adoc

The `size()` operator cannot be used to count graph patterns in v5 anymore. Therefore, the docs need to be changed to `count {}` operator.

Replace size() with count {}

---

modules/ROOT/pages/languages-guides/neo4j-php.adoc

Copy of https://github.com/neo4j-documentation/developer-guides/pull/273

Update bolt library specs by latest major update (#173)

---

antora.yml
modules/ROOT/pages/languages-guides/java/java-intro.adoc
modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc
modules/ROOT/pages/languages-guides/java/spring-data-neo4j.adoc
modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc
modules/ROOT/pages/languages-guides/neo4j-go.adoc
modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
modules/ROOT/pages/languages-guides/neo4j-python.adoc

Complement antora.yml with the drivers' version numbers.
Remove those attributes from the corresponding files.

Update the attributes' list in the antora.yml file

---

modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/cypher-intro/large-statements.adoc
modules/ROOT/pages/cypher-intro/load-csv.adoc
modules/ROOT/pages/cypher-intro/patterns-in-practice.adoc
modules/ROOT/pages/cypher-intro/patterns.adoc
modules/ROOT/pages/cypher-intro/procedures-functions.adoc
modules/ROOT/pages/cypher-intro/resources.adoc
modules/ROOT/pages/cypher-intro/results.adoc
modules/ROOT/pages/cypher-intro/schema.adoc

* Add GraphAcademy button to the Cypher section
* Set a link directly to the Cypher course
* Set up a link to the Cypher course
* Set up a link directly to the Cypher course
* Update patterns.adoc
* Update a link to the Cypher course
* Update a link to Cypher course
* Update resources.adoc

Add GraphAcademy button to the Cypher section (#181)

---

modules/ROOT/pages/data-import/index.adoc
modules/ROOT/pages/data-modeling/index.adoc
modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
modules/ROOT/pages/get-started-with-neo4j/index.adoc
modules/ROOT/pages/index.adoc
modules/ROOT/pages/languages-guides/index.adoc

* Add links to the GraphAcademy courses
* Update graph-database.adoc

Add links to the GraphAcademy courses (#188)

---

modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc

Fixing broken link to dot net api

---

modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/203

fixing broken link to dot net api (#203)

---

modules/ROOT/pages/languages-guides/index.adoc

Rename the section on Neo4j drivers
Update the first page of the section

Rename drivers section

---

modules/ROOT/pages/languages-guides/index.adoc

* Rename drivers section
* Update modules/ROOT/pages/languages-guides/index.adoc
---------

Rename drivers section (#217)

---

antora.yml
modules/ROOT/pages/index.adoc

Add an attribute to the antora.yml file: 'neo4j-version-minor'

Update Neo4j version

---

modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-nosql.adoc
modules/ROOT/pages/appendix/graphdb-concepts/graphdb-vs-rdbms.adoc
modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
modules/ROOT/pages/index.adoc

Adds a title that can be displayed as the PDF title and provides a `link:` for embedded videos, which can't be included in a PDF.

Fixes for PDF

---

modules/ROOT/pages/appendix/example-data.adoc
modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
modules/ROOT/pages/cypher-intro/procedures-functions.adoc
modules/ROOT/pages/data-import/json-rest-api-import.adoc
modules/ROOT/pages/data-import/relational-to-graph-import.adoc
modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
modules/ROOT/pages/data-modeling/modeling-tips.adoc
modules/ROOT/pages/languages-guides/java/java-procedures.adoc

* Update links to the APOC docs
* Update example-data.adoc
* Update example-data.adoc
* Update modules/ROOT/pages/appendix/example-data.adoc
* Update example-data.adoc

Update links to the APOC docs (#224)

---

modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc
modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
modules/ROOT/pages/languages-guides/community-drivers/java-third-party.adoc
modules/ROOT/pages/languages-guides/community-drivers/neo4j-ruby.adoc

Changing links from http to https for better indexation 

---

modules/ROOT/pages/appendix/tutorials/guide-build-a-recommendation-engine.adoc
modules/ROOT/pages/data-modeling/guide-data-modeling.adoc
modules/ROOT/pages/languages-guides/community-drivers/neo4j-ruby.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/236

Changing links from http to https for better indexation  (#236)

---

modules/ROOT/pages/cypher-intro/procedures-functions.adoc

* Update content on how to extend Cypher
* Update procedures-functions.adoc
* Update procedures-functions.adoc

Update content on how to extend Cypher (#243)

---

antora.yml
publish.yml

Remove versions

---

modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc

Implement updates to the page on .Net driver

---

modules/ROOT/pages/languages-guides/neo4j-dotnet.adoc

See PRs #207 and #226.
Somehow the PR #226 was merged without commits of the PR#207.
This new PR is to implement approved commits from the PR #207.

Implement updates to the page on .Net driver (#251)

---

README.adoc

Since the GSG is unversioned, the instructions on how to contribute to this repo have to be updated.

Update README.adoc (#250)

---

modules/ROOT/pages/appendix/tutorials/guide-cypher-basics.adoc
modules/ROOT/pages/cypher-intro/index.adoc
modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
modules/ROOT/pages/get-started-with-neo4j/index.adoc
modules/ROOT/pages/graph-visualization/graph-visualization.adoc
modules/ROOT/pages/index.adoc
package.json
preview.yml
publish.yml

* Add the trademark icon on the 1st usage of Cypher
* Update graph-model-refactoring.adoc
* Update graph-visualization.adoc
* Update guide-cypher-basics.adoc
* Update guide-cypher-basics.adoc

Add the trademark icon on the 1st usage of Cypher (#268)

---

modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
modules/ROOT/pages/cypher-intro/index.adoc

Not sure how the versioning is working now on the getting started guide, but this might need to be cherry-picked to 5.x? 😊

Broken links to Cypher new section on values and types

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/appendix/tutorials/guide-import-desktop-csv.adoc
modules/ROOT/pages/get-started-with-neo4j/graph-database.adoc
modules/ROOT/pages/index.adoc
modules/ROOT/pages/languages-guides/index.adoc
modules/ROOT/pages/languages-guides/java/java-frameworks.adoc
modules/ROOT/pages/languages-guides/java/quarkus.adoc

* Publish branches
* Update the first pages with a new image and restructure them (#161)
* Update the first pages with a new image and restructure them
* Update graph-database.adoc
* Update graph-database.adoc
* Update graph-database.adoc
* Update tutorials on how to import CSV files (#166)
* Update tutorials on how to import CSV files
* Update load-csv.adoc
* Update load-csv.adoc
* Update load-csv.adoc
* Update guide-import-desktop-csv.adoc
* Update …

Added Quarkus guide page (#172)

---

modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc
modules/ROOT/pages/cypher-intro/index.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/275

Broken links to Cypher new section on values and types (#275)

---

modules/ROOT/content-nav.adoc
modules/ROOT/pages/gds/end-to-end-example.adoc
modules/ROOT/pages/gds/index.adoc

* Create a new section on GDS
* Create a new section on GDS
* Implement suggestions from the code review
* Add paragraphs about Bloom and connectors
---------

Add a new section on GDS (#258)

---

modules/ROOT/pages/get-started-with-neo4j/index.adoc
modules/ROOT/pages/index.adoc

- Clean up the file
- Editorial tweaks
- Update links according to the changes on the main website
- Remove mentions of the Neo4j Graph Data Platform as this term is not used on the main website

Update links according to the website changes (#286)

---

modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc

Reverts neo4j/docs-getting-started#260

Revert "update neo4j-ogm.adoc"

---

modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc

Reverts neo4j/docs-getting-started#289

Revert "Revert "update neo4j-ogm.adoc""

---

modules/ROOT/pages/cypher-intro/results.adoc

Based on the following Trello card: https://trello.com/c/7kPGMtkE

Remove possible contradictions between the GSG and the Cypher manual

---

modules/ROOT/pages/languages-guides/community-drivers/index.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/294

Broken external link (#294)

---

modules/ROOT/pages/cypher-intro/results.adoc

* Explain the query result
* Update list formatting

Explain the query result (#305)

---

modules/ROOT/pages/get-started-with-neo4j/index.adoc

* Add information about plugins
* Add the link to the GDS Sandbox

Add information about plugins (#308)

---

modules/ROOT/pages/data-modeling/modeling-designs.adoc

"Time-bound data and versioning" section reffering to Figure 3 when it should be Figure 4.

Update modeling-designs.adoc (#314)

---

modules/ROOT/pages/appendix/graphdb-concepts/index.adoc

Fix small omission on the Cypher example to match de graph viz. https://neo4j.com/docs/getting-started/appendix/graphdb-concepts/#graphdb-example-graph

Update index.adoc Cypher example (#327)

---

modules/ROOT/pages/data-import/csv-import.adoc

Add a link to the 4.4 docs following the user's request.
https://trello.com/c/pYrCslls

Add a link to the v4.4 about the command `neo4j-admin import`

---

modules/ROOT/pages/cypher-intro/subqueries.adoc

* Add information about the `COLLECT` subqueries
* Update modules/ROOT/pages/cypher-intro/subqueries.adoc
* Remove the word `expression` from `subquery expression`
---------

Add information about the `COLLECT` subqueries (#334)

---

modules/ROOT/pages/languages-guides/index.adoc
modules/ROOT/pages/languages-guides/neo4j-javascript.adoc

* Redesign the JavaScript driver page
* Update modules/ROOT/pages/languages-guides/neo4j-javascript.adoc
* Update neo4j-javascript.adoc
---------

Redesign the JavaScript driver page (#339)

---

modules/ROOT/pages/cypher-intro/patterns.adoc

* Add links to the Cypher docs
* Update modules/ROOT/pages/cypher-intro/patterns.adoc
---------

Add links to the Cypher docs (#341)

---

modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc

* Update Cypher syntax for showing indexes
* Update modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
* Update modules/ROOT/pages/appendix/tutorials/guide-import-relational-and-etl.adoc
* Add two def.columns to the table
* Add two columns to the result table
---------

Update Cypher syntax for showing indexes (#349)

---

modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc

* Add a link to the Cypher manual and fix links to the APOC docs
* Update modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
* Update modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
* Update modules/ROOT/pages/data-modeling/graph-model-refactoring.adoc
---------

Add a link to the Cypher manual and fix links to the APOC docs (#379)

---

modules/ROOT/pages/data-import/relational-to-graph-import.adoc

PR is opened to address [the Trello card](https://trello.com/c/Y9Mo2wJW). There is a request to replace Kettle with Apache Hop.

Add information about Apache Hop, remove Kettle

---

modules/ROOT/pages/data-import/relational-to-graph-import.adoc

* Add information about Apache Hop, remove Kettle
* Update modules/ROOT/pages/data-import/relational-to-graph-import.adoc
* Update modules/ROOT/pages/data-import/relational-to-graph-import.adoc
* Update relational-to-graph-import.adoc
---------

Add information about Apache Hop, remove Kettle (#368)

---

modules/ROOT/pages/appendix/example-data.adoc

* Update example datasets page
* Update modules/ROOT/pages/appendix/example-data.adoc

Update example datasets page (#383)

---

modules/ROOT/pages/languages-guides/java/quarkus.adoc
modules/ROOT/pages/languages-guides/neo4j-go.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/395

Fixing ASCIIDoc error for tables (#395)

---

modules/ROOT/pages/index.adoc

Add GA banner

---

modules/ROOT/pages/languages-guides/index.adoc

As requested by PM, add Query API before HTTP API.
While I was at it I also trimmed other content around, but I will come back with a more proper review of the page later.
This should have been committed to `dev` (see #412), but the build is broken so it's currently not possible.

Add Query API 

---

modules/ROOT/pages/languages-guides/index.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/413

Add Query API, polish around. (#413)

---

modules/ROOT/pages/languages-guides/java/neo4j-ogm.adoc

Fix the OGM page (#431)

---

modules/ROOT/pages/cypher-intro/dates-datetimes-durations.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/443

Adding link for more datetime function info (#443)

---

modules/ROOT/pages/graph-visualization/graph-visualization.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/447

Fix typos #447

---

modules/ROOT/pages/data-import/csv-import.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/449

Include links to neo4j-admin and data importer docs (#449)

---

modules/ROOT/pages/graph-visualization/graph-visualization-tools.adoc

* add nvl and some style stuff
* extra line

Add nvl (#467)

---

modules/ROOT/pages/cypher.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/471

fix (#471)

---

modules/ROOT/pages/data-modeling/data-modeling-tools.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/487

Clarifying information about tools (#487)

---

modules/ROOT/pages/graph-visualization/graph-visualization-tools.adoc

Cherry-picked from https://github.com/neo4j/docs-getting-started/pull/478

add GraphAware Hume to visualisation tools (#478)
